### PR TITLE
fix: #1798 rewind not setting gravity to false on log out

### LINKED ISSUE #1798: Quitting world while being moved by rewind and creative flying softlocks the game
Footage: https://streamable.com/68n0k5

### PR DESCRIPTION
**Pull request by Vonr**
fixes #1798

### CODE REVIEW

File: src/main/java/com/hollingsworth/arsnouveau/common/event/timed/RewindEvent.java [hunk 1]
```diff
@@ -86,6 +100,18 @@ public void onServerStopping() {
...
     }
 
+    public void onEntityRemoved(PlayerEvent.PlayerLoggedOutEvent event) {
+        if (entity == null) {
+            NeoForge.EVENT_BUS.unregister(this);
+            return;
+        }
+
+        if (entity == event.getEntity() && event.getEntity().isNoGravity()) {
+            event.getEntity().setNoGravity(false);
```
Comment (baileyholl) [inline src/main/java/com/hollingsworth/arsnouveau/common/event/timed/RewindEvent.java:110]: I think we would need to check if they were affected by gravity at the start, otherwise this will disable gravity from mobs that were originally noGravity = true.
